### ISSUE TITLE
Error: Invalid __Secure-1PSID or __Secure-3PSID value. Please ensure you provide a valid __Secure-1PSID or __Secure-3PSID value.

### ISSUE THREAD

**Issue by ahlulmukh** [codenze/bard-api-node#5]
get this error

**Comment by HiagoSouz** [comment]
Clear your cookies or use incognito mode and try again. It will work.

**Comment by ahlulmukh** [comment]
> Clear your cookies or use incognito mode and try again. It will work.

thankyou <3
