### ISSUE TITLE
Error: TypeError: Cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by HiagoSouz** [codenze/bard-api-node#6]
I keep getting this issue related to this line in bardAPI.js

`Error: TypeError: Cannot read properties of null (reading '0')`

This appears to be affecting this line: parsed_answer[2][0] - (textQuery parameter);

I didn't find where the package uses this parameter and the content with the response is not being affected.

I removed the object line to avoid the problem here, but perhaps a solution for this was needed directly in the package.

**Comment by codenze** [comment]
Hi @HiagoSouz,

I wanted to express my gratitude for reporting [issue(s)] on our repository. Thanks to your feedback, I've released an upgraded version (2.0.0) that addresses these issues.

This update ensures better accessibility and compatibility with official Google APIs, though it took some time. Your patience and support are greatly appreciated.

Thanks again for your contribution!

Best regards,
@codenze
