### ISSUE TITLE
Does this still work? Error: Failed to retrieve SNlM0e pattern.

### ISSUE THREAD

**Issue by Cinemacloud** [codenze/bard-api-node#8]
I've tried several go, python, and your library and all seem to have this type of issue.
I've rechecked all my 1P and 3P values and they're correct. I even tweaked the conversation ID
constant you have hardcoded to my own in case that was issue. 

Error: Failed to retrieve SNlM0e pattern. Please ensure you provide a valid __Secure-1PSID or __Secure-3PSID value.
    at BardAPI.setSnim0e (/root/node_modules/bard-api-node/src/bardAPI.js:113:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BardAPI.setSession (/root/node_modules/bard-api-node/src/bardAPI.js:36:5)
    at async testAssistant (/root/test.js:7:5)
Bard: Authentication Error! Please make sure to initialize with the correct __Secure-1PSID or __Secure-3PSID value.

**Comment by vEduardovich** [comment]
Me neither

**Comment by Cinemacloud** [comment]
I'm making an unbreakable Bard/any LLM API no keys or complexity required..

**Comment by codenze** [comment]
Hi @Cinemacloud ,

I wanted to express my gratitude for reporting [issue(s)] on our repository. Thanks to your feedback, I've released an upgraded version (2.0.0) that addresses these issues.

This update ensures better accessibility and compatibility with official Google APIs, though it took some time. Your patience and support are greatly appreciated.

Thanks again for your contribution!

Best regards,
@codenze
